dist: xenial
sudo: false

language: node_js
node_js:
  - '10'

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script build
  - dist/apps/doc
  - cp index.html 404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/apps/doc
  on:
    branch: master
